CREATE DATABASE StudentNumber_DATA6222_ExamQ1;CREATE DATABASE StudentNumber_DATA6222_ExamQ1;

CREATE TABLE Student ( 
	STUDENT_ID INT PRIMARY KEY,
	StudentName VARCHAR(50),
	StudentCell VARCHAR(10)
);

CREATE TABLE TUTOR(
	TUTOR_ID INT PRIMARY KEY,
	TutorName VARCHAR(100),
	TutorAddress VARCHAR(100)
)
